server:
  port: 8071
spring:
  profiles:
    active:
      #- native
      - git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/tech2java/tech2java-config.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

        #native:
          #search-locations: "classpath:/config"
          #search-locations: "file:///E://config"

  application:
    name: configserver
encrypt:
  key: "iVu5FuDmo/NSpZUioH8PhEOYK4Jh6atVXbjM4R4XA+4zYxYGKrtw/t/n4ChdWkAu"